### ISSUE TITLE
Multi-Language

### ISSUE THREAD

**Issue by mambax7** [JJDai54/trombinoscope#5]
It would be nice to have a multi-language solution, instead of the hard-coded category names:

```sql
INSERT INTO trombinoscope_categories (`cat_id`, `cat_parent_id`, `cat_name`, `cat_weight`, `cat_theme`) VALUES
(1, 0, 'Membres', 0, ''),
(2, 0, 'Donnateurs', 10, ''),
(3, 0, 'Partenaires', 20, '');
```

**Comment by JJDai54** [comment]
yes I know, but since until now I was the only one using my modules, that didn't worry me.
And I don't see how to do it, these are default category names, the user can modify them in the language of their choice.
I can leave the table empty at install, but I don't think that's a good idea.

**Comment by mambax7** [comment]
I fixed that - see if it works for you:
https://github.com/mambax7/trombinoscope/commit/59ca64c4245e2c55ca69a17173d6c1af8ca659e7

**Comment by mambax7** [comment]
BTW - this was just "quick and dirty", but in the future we'll have to make it more generic, i.e. add the SQL as part of installation config of the specific module, and the installation function will check if there is any SQL to install, and if yes, then run it.

**Comment by JJDai54** [comment]
ok
