### ISSUE TITLE
Not possible to Edit category

### ISSUE THREAD

**Issue by mambax7** [JJDai54/trombinoscope#6]
I tried to edit the Category name:

![image](https://github.com/JJDai54/trombinoscope/assets/613686/58cbf866-8be7-43ce-9570-b0e0138fd62a)

but it showed me a blank screen with the title "Add Category"

![image](https://github.com/JJDai54/trombinoscope/assets/613686/fc68efc0-f5a6-4dd1-b8b7-f5cb8290b306)

**Comment by mambax7** [comment]
But when I clicked on the link:

![image](https://github.com/JJDai54/trombinoscope/assets/613686/f33826e8-2996-4883-ab37-e705bf82fd33)

it opened the Edit form:

![image](https://github.com/JJDai54/trombinoscope/assets/613686/bae87475-36f4-463f-9aea-e9a6796d1e52)

**Comment by JJDai54** [comment]
ok I corrected, the smarty variable in the template was $category instead of $cat

**Comment by JJDai54** [comment]
for information
src="<{xoModuleIcons16 'editcopy.png'}>"
doesn't work in French because of the apostrophes, I replaced pae:
src="<{xoModuleIcons16}>editcopy.png"

**Comment by JJDai54** [comment]
end
