### ISSUE TITLE
Framework Date issue

### ISSUE THREAD

**Issue by mambax7** [JJDai54/trombinoscope#7]
When I tried to add a new member, I've got this error:

` TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, false given in file /Frameworks/JJD-Framework/include/date-functions.php line 34`

![image](https://github.com/JJDai54/trombinoscope/assets/613686/a0a8adad-676d-4785-91c6-4495dc239278)

Maybe there is a conflict between English and French formats?

**Comment by JJDai54** [comment]
Indeed probably due to the French format.
I'm installing an English version and looking at it as soon as possible.

**Comment by JJDai54** [comment]
i have change  in english/*common.php
define('_CO_TROMBINOSCOPE_FORMAT_DATE_SHORT', "Y-m-d");
for
define('_CO_TROMBINOSCOPE_FORMAT_DATE_SHORT', "m/d/Y");

and i have modified then fonction "getDateSql" in JJD-Framework
one of the probleme was different separator betwen date-string and format-string
now it convert all two with "-" before to make date
        //harmonisation des separateur, la fonction date_create_from_format y est sensible
        $dateVar = str_replace ('/','-',$dateVar);
        $formatFrom = str_replace ('/','-',$formatFrom);

**Comment by mambax7** [comment]
Instead of hardcoding it in the module, we should pull the _SHORTDATESTRING from the \language\english\global.php, which for English is:

`define('_SHORTDATESTRING', 'm/d/Y');`

**Comment by JJDai54** [comment]
it's done
